import type { InteractionDefinition, InteractionAction } from '../interactions/types';
import type { HouseObjectDefinition } from './types';

const action = (id: string, label: string, conditions: readonly string[] = [], effects: readonly string[] = []): InteractionAction => ({ id, label, conditions, effects });
const interaction = (
  actions: InteractionAction[],
  approachPoint: { x: number; y: number },
  actionPoint: { x: number; y: number },
  facing: InteractionDefinition['facing'],
  type: InteractionDefinition['type'] = 'important',
  priority = 80,
  radius = 88,
  persistentState?: string
): HouseObjectDefinition['interaction'] => ({ actions, approachPoint, actionPoint, facing, type, priority, radius, persistentState });

/**
 * Blueprint-driven House V3 object placement.
 * The registry keeps the existing interaction ids, while aligning the visual composition
 * more closely with the approved house blueprint.
 */
export const HOUSE_OBJECTS: readonly HouseObjectDefinition[] = [
  // BEDROOM
  { id: 'bedroom-window', label: 'Raam en gordijnen', room: 'bedroom', render: { texture: 'bedroom-window', x: 220, y: 76, layer: 'wall' }, interaction: interaction([action('open-window','Raam openen'),action('close-window','Raam sluiten'),action('toggle-curtains','Gordijnen openen / sluiten'),action('look-outside','Naar buiten kijken')], {x:220,y:144},{x:220,y:76},'up','important',80,82,'windowOpen'), sourceAsset: 'Modern Interiors 48x48 / Bedroom Singles 119' },
  { id: 'bedroom-art', label: 'Poster', room: 'bedroom', render: { texture: 'bedroom-art', x: 110, y: 66, layer: 'wall', scale: 0.75 }, sourceAsset: 'Modern Interiors 48x48 / Bedroom Singles 479' },
  { id: 'bedroom-rug', label: 'Vloerkleed', room: 'bedroom', render: { texture: 'bedroom-rug', x: 142, y: 190, layer: 'floor', scale: 1.15 }, sourceAsset: 'Modern Interiors 48x48 / Bedroom Singles 381' },
  { id: 'bed', label: 'Bed', room: 'bedroom', render: { texture: 'bed', x: 104, y: 144 }, collision: {x:48,y:88,w:112,h:94}, interaction: interaction([action('sit','Op de rand zitten'),action('lie','Gaan liggen'),action('sleep','Slapen'),action('stand','Opstaan'),action('make','Bed opmaken')], {x:185,y:166},{x:144,y:144},'left','important',80,90,'bedMade'), sourceAsset: 'Modern Interiors 48x48 / Bedroom Singles' },
  { id: 'nightstand', label: 'Nachtkastje', room: 'bedroom', render: { texture: 'side-table', x: 176, y: 101 }, collision: {x:157,y:68,w:38,h:45}, interaction: interaction([action('open-drawer','Lade openen'),action('close-drawer','Lade sluiten'),action('examine','Bekijken')], {x:178,y:150},{x:176,y:101},'up','important',80,72,'nightstandOpen'), sourceAsset: 'Modern Interiors 48x48 / Living Room Singles 45' },
  { id: 'bedside-lamp', label: 'Nachtlamp', room: 'bedroom', render: { texture: 'bedside-lamp-on', x: 176, y: 76, layer: 'surface' }, interaction: interaction([action('toggle','Licht aan / uit')], {x:178,y:150},{x:176,y:80},'up','important',80,72), sourceAsset: 'Modern Interiors 48x48 / Bedroom lamp derivative' },
  { id: 'alarm-clock', label: 'Wekker', room: 'bedroom', render: { texture: 'alarm-clock', x: 192, y: 93, layer: 'surface', scale: 1.5 }, interaction: interaction([action('stop','Uitzetten'),action('snooze','Sluimeren'),action('set','Tijd instellen')], {x:178,y:150},{x:192,y:93},'up','important',80,72,'alarmState'), sourceAsset: 'QUOTIDIANO project-owned pixel prop' },
  { id: 'desk', label: 'Bureau', room: 'bedroom', render: { texture: 'desk', x: 226, y: 112 }, collision: {x:176,y:88,w:98,h:42}, interaction: interaction([action('sit','Gaan zitten'),action('write','Schrijven'),action('stand','Opstaan')], {x:226,y:164},{x:226,y:112},'up','seat',50,86), sourceAsset: 'Modern Interiors 48x48 / Living Room Singles 29' },
  { id: 'laptop', label: 'Laptop', room: 'bedroom', render: { texture: 'laptop', x: 226, y: 98, layer: 'surface' }, interaction: interaction([action('toggle','Aan / uit'),action('email','E-mail openen')], {x:226,y:164},{x:226,y:100},'up','important',80,82,'laptopOn'), sourceAsset: 'QUOTIDIANO project-owned pixel prop' },
  { id: 'wardrobe', label: 'Kledingkast', room: 'bedroom', render: { texture: 'wardrobe-closed-v3', x: 306, y: 144 }, collision: {x:264,y:86,w:80,h:116}, interaction: interaction([action('toggle','Openen / sluiten'),action('dress','Kleding kiezen'),action('store-clothes','Kleding opbergen')], {x:288,y:222},{x:306,y:144},'up','important',80,92,'wardrobeOpen'), sourceAsset: 'Modern Interiors 48x48 / Bedroom Singles 538–539' },
  { id: 'backpack', label: 'Rugzak', room: 'bedroom', render: { texture: 'backpack', x: 300, y: 236 }, interaction: interaction([action('take','Pakken'),action('leave','Neerzetten'),action('inspect','Inhoud bekijken')], {x:274,y:244},{x:300,y:236},'right','inventory',70,70), sourceAsset: 'Modern Interiors 48x48 / Bedroom Singles 437' },
  { id: 'bedroom-plant', label: 'Plant', room: 'bedroom', render: { texture: 'plant', x: 78, y: 246 }, collision: {x:60,y:214,w:34,h:44}, sourceAsset: 'Modern Interiors 48x48 / Living Room Singles 15' },

  // BATHROOM
  { id: 'bathroom-mat', label: 'Badmat', room: 'bathroom', render: { texture: 'bathroom-mat', x: 515, y: 232, layer: 'floor' }, sourceAsset: 'Modern Interiors 48x48 / Bathroom Singles 77' },
  { id: 'bathroom-mirror', label: 'Spiegel', room: 'bathroom', render: { texture: 'bathroom-mirror', x: 424, y: 72, layer: 'wall' }, interaction: interaction([action('look','Kijken'),action('hair','Haar doen')], {x:424,y:164},{x:424,y:72},'up','observation',20,76), sourceAsset: 'Modern Interiors 48x48 / Bathroom Singles 66' },
  { id: 'bathroom-sink', label: 'Wastafel', room: 'bathroom', render: { texture: 'bathroom-sink', x: 424, y: 114 }, collision: {x:384,y:68,w:80,h:68}, interaction: interaction([action('wash-hands','Handen wassen'),action('wash-face','Gezicht wassen')], {x:424,y:168},{x:424,y:114},'up','important',80,80), sourceAsset: 'Modern Interiors 48x48 / Bathroom Singles' },
  { id: 'toothbrush', label: 'Tandenborstel', room: 'bathroom', render: { texture: 'toothbrush-cup', x: 458, y: 112, layer: 'surface' }, interaction: interaction([action('take','Pakken'),action('brush','Tanden poetsen'),action('store','Terugzetten')], {x:452,y:168},{x:458,y:112},'up','inventory',70,72), sourceAsset: 'QUOTIDIANO project-owned pixel prop' },
  { id: 'shower', label: 'Douche', room: 'bathroom', render: { texture: 'shower', x: 530, y: 112 }, collision: {x:492,y:48,w:76,h:114}, interaction: interaction([action('shower','Douchen')], {x:486,y:174},{x:518,y:164},'right','important',80,92,'showeredToday'), sourceAsset: 'Modern Interiors 48x48 / Bathroom Singles' },
  { id: 'toilet', label: 'Toilet', room: 'bathroom', render: { texture: 'toilet', x: 402, y: 222 }, collision: {x:380,y:184,w:42,h:74}, interaction: interaction([action('use','Gebruiken'),action('flush','Doorspoelen')], {x:450,y:224},{x:402,y:222},'left','important',80,76), sourceAsset: 'Modern Interiors 48x48 / Bathroom Singles' },
  { id: 'bathroom-shelf', label: 'Badkamerkast', room: 'bathroom', render: { texture: 'bathroom-shelf', x: 553, y: 220 }, collision: {x:525,y:184,w:52,h:70}, interaction: interaction([action('open','Openen'),action('take-products','Verzorgingsproducten pakken'),action('close','Sluiten')], {x:506,y:232},{x:553,y:220},'right','important',80,78), sourceAsset: 'Modern Interiors 48x48 / Bathroom Singles 83' },
  { id: 'towel-rack', label: 'Handdoek', room: 'bathroom', render: { texture: 'towel-rack', x: 476, y: 117, layer: 'wall' }, interaction: interaction([action('take','Pakken'),action('use','Afdrogen'),action('hang','Ophangen')], {x:476,y:170},{x:476,y:117},'up','inventory',70,66), sourceAsset: 'Modern Interiors 48x48 / Bathroom Singles 143' },
  { id: 'bathroom-bin', label: 'Prullenbak', room: 'bathroom', render: { texture: 'bathroom-bin', x: 546, y: 256 }, interaction: interaction([action('discard','Afval weggooien')], {x:516,y:254},{x:546,y:256},'right','important',80,65), sourceAsset: 'Modern Interiors 48x48 / Bathroom Singles 138' },
  { id: 'bathroom-plant', label: 'Plant', room: 'bathroom', render: { texture: 'plant', x: 402, y: 258 }, sourceAsset: 'Modern Interiors 48x48 / Living Room Singles 15' },

  // KITCHEN / DINING
  { id: 'oven', label: 'Fornuis', room: 'kitchen', render: { texture: 'oven', kind: 'sprite', x: 636, y: 108, frame: 0 }, collision: {x:612,y:58,w:54,h:84}, interaction: interaction([action('toggle','Aan / uit'),action('cook','Koken')], {x:640,y:174},{x:636,y:108},'up','important',80,86,'ovenOn'), sourceAsset: 'Modern Interiors 48x48 / Kitchen Singles' },
  { id: 'kitchen-sink', label: 'Aanrecht en gootsteen', room: 'kitchen', render: { texture: 'kitchen-counter', x: 772, y: 106 }, collision: {x:700,y:62,w:144,h:72}, interaction: interaction([action('wash-hands','Handen wassen'),action('wash-food','Eten wassen'),action('wash-dishes','Afwas doen')], {x:772,y:174},{x:772,y:106},'up','important',80,86), sourceAsset: 'Modern Interiors 48x48 / Kitchen Singles' },
  { id: 'coffee', label: 'Koffiezetapparaat', room: 'kitchen', render: { texture: 'coffee', kind: 'sprite', x: 804, y: 110, frame: 0, layer: 'surface' }, interaction: interaction([action('brew','Koffie zetten'),action('take','Kopje pakken')], {x:804,y:174},{x:804,y:110},'up','important',80,82,'coffeeReady'), sourceAsset: 'Modern Interiors 48x48 / Kitchen Singles' },
  { id: 'toaster', label: 'Broodrooster', room: 'kitchen', render: { texture: 'toaster', kind: 'sprite', x: 754, y: 110, frame: 0, layer: 'surface' }, interaction: interaction([action('toast','Brood roosteren')], {x:754,y:174},{x:754,y:110},'up','important',80,82,'toastReady'), sourceAsset: 'Modern Interiors 48x48 / Kitchen Singles' },
  { id: 'fridge', label: 'Koelkast', room: 'kitchen', render: { texture: 'fridge', kind: 'sprite', x: 880, y: 126, frame: 0 }, collision: {x:850,y:62,w:64,h:116}, interaction: interaction([action('toggle','Openen / sluiten'),action('take-breakfast','Brood pakken'),action('put-back','Terugzetten')], {x:880,y:196},{x:880,y:126},'up','important',80,96,'fridgeOpen'), sourceAsset: 'Modern Interiors 48x48 / Kitchen Singles' },
  { id: 'kitchen-bin', label: 'Afvalbak', room: 'kitchen', render: { texture: 'bathroom-bin', x: 678, y: 150 }, interaction: interaction([action('discard','Afval weggooien')], {x:704,y:178},{x:678,y:150},'left','important',80,68), sourceAsset: 'Modern Interiors 48x48 / Bathroom Singles 138' },
  { id: 'dining-table', label: 'Eettafel', room: 'kitchen', render: { texture: 'dining-table', x: 786, y: 286 }, collision: {x:738,y:246,w:96,h:72}, interaction: interaction([action('place-breakfast','Ontbijt neerzetten'),action('sit','Gaan zitten'),action('eat','Ontbijten'),action('drink','Drinken'),action('stand','Opstaan')], {x:786,y:342},{x:786,y:286},'up','seat',50,98,'breakfastEaten'), sourceAsset: 'Modern Interiors 48x48 / Kitchen Singles' },
  { id: 'dining-chair-left', label: 'Eetkamerstoel', room: 'kitchen', render: { texture: 'dining-chair', x: 710, y: 286 }, collision: {x:692,y:260,w:36,h:42}, sourceAsset: 'Modern Interiors 48x48 / Living Room Singles' },
  { id: 'dining-chair-right', label: 'Eetkamerstoel', room: 'kitchen', render: { texture: 'dining-chair', x: 862, y: 286, flipX: true }, collision: {x:844,y:260,w:36,h:42}, sourceAsset: 'Modern Interiors 48x48 / Living Room Singles' },
  { id: 'breakfast-plate', label: 'Ontbijtbord', room: 'kitchen', render: { texture: 'breakfast-plate', x: 775, y: 270, layer: 'surface', visible: false }, sourceAsset: 'Modern Interiors 48x48 / Kitchen Singles' },
  { id: 'coffee-serving', label: 'Koffiekop', room: 'kitchen', render: { texture: 'coffee-serving', x: 806, y: 272, layer: 'surface', visible: false }, sourceAsset: 'Modern Interiors 48x48 / Kitchen Singles' },
  { id: 'kitchen-plant', label: 'Keukenplant', room: 'kitchen', render: { texture: 'plant', x: 896, y: 294 }, collision: {x:880,y:260,w:32,h:44}, interaction: interaction([action('observe','Bekijken'),action('water','Water geven')], {x:864,y:320},{x:896,y:294},'right','observation',20,66), sourceAsset: 'Modern Interiors 48x48 / Living Room Singles 15' },

  // LIVING ROOM
  { id: 'living-rug', label: 'Vloerkleed', room: 'living', render: { texture: 'bedroom-rug', x: 250, y: 498, layer: 'floor', scale: 2.1 }, sourceAsset: 'Modern Interiors 48x48 / Bedroom Singles 381' },
  { id: 'tv', label: 'Televisie', room: 'living', render: { texture: 'tv', x: 262, y: 357 }, collision: {x:218,y:316,w:88,h:70}, interaction: interaction([action('toggle','Aan / uit'),action('watch','Even kijken')], {x:262,y:411},{x:262,y:357},'up','important',80,86,'tvOn'), sourceAsset: 'Modern Interiors 48x48 / Living Room Singles' },
  { id: 'bookshelf', label: 'Boekenkast', room: 'living', render: { texture: 'bookshelf', x: 78, y: 454 }, collision: {x:58,y:410,w:40,h:76}, interaction: interaction([action('examine','Bekijken'),action('take-book','Boek pakken'),action('read-book','Lezen'),action('return-book','Terugzetten')], {x:120,y:456},{x:78,y:454},'left','important',80,82), sourceAsset: 'Modern Interiors 48x48 / Living Room Singles 122' },
  { id: 'living-plant', label: 'Kamerplant', room: 'living', render: { texture: 'plant', x: 126, y: 392 }, collision: {x:110,y:356,w:32,h:46}, interaction: interaction([action('observe','Bekijken'),action('water','Water geven')], {x:154,y:418},{x:126,y:392},'left','observation',20,70), sourceAsset: 'Modern Interiors 48x48 / Living Room Singles 15' },
  { id: 'coffee-table', label: 'Salontafel', room: 'living', render: { texture: 'coffee-table', x: 250, y: 463 }, collision: {x:205,y:430,w:90,h:55}, interaction: interaction([action('place-item','Iets neerzetten'),action('take-item','Iets pakken')], {x:328,y:472},{x:250,y:463},'left','important',80,82), sourceAsset: 'Modern Interiors 48x48 / Living Room Singles 51' },
  { id: 'sofa', label: 'Bank', room: 'living', render: { texture: 'sofa', x: 250, y: 580 }, collision: {x:198,y:562,w:104,h:42}, interaction: interaction([action('sit','Zitten'),action('relax','Ontspannen'),action('stand','Opstaan')], {x:250,y:628},{x:250,y:574},'up','seat',50,92), sourceAsset: 'Modern Interiors 48x48 / Living Room Singles' },
  { id: 'living-lamp', label: 'Staande lamp', room: 'living', render: { texture: 'floor-lamp', x: 120, y: 580 }, collision: {x:104,y:546,w:32,h:58}, interaction: interaction([action('toggle','Aan / uit')], {x:156,y:592},{x:120,y:580},'left','important',80,76,'livingLightOn'), sourceAsset: 'Modern Interiors 48x48 / Living Room Singles 86' },
  { id: 'side-table', label: 'Bijzettafel', room: 'living', render: { texture: 'side-table', x: 380, y: 565 }, collision: {x:362,y:536,w:36,h:45}, interaction: interaction([action('place-item','Iets neerzetten'),action('take-item','Iets pakken')], {x:344,y:580},{x:380,y:565},'right','important',80,68), sourceAsset: 'Modern Interiors 48x48 / Living Room Singles 45' },
  { id: 'living-side-plant', label: 'Plant', room: 'living', render: { texture: 'plant', x: 408, y: 608 }, collision: {x:392,y:574,w:30,h:46}, sourceAsset: 'Modern Interiors 48x48 / Living Room Singles 15' },

  // ENTRY / HALL
  { id: 'entry-plant', label: 'Plant', room: 'entry', render: { texture: 'plant', x: 522, y: 404 }, collision: {x:506,y:370,w:32,h:46}, sourceAsset: 'Modern Interiors 48x48 / Living Room Singles 15' },
  { id: 'entry-console', label: 'Halmeubel', room: 'entry', render: { texture: 'entry-console', x: 616, y: 404 }, collision: {x:570,y:364,w:94,h:66}, interaction: interaction([action('examine','Bekijken'),action('place-item','Iets neerleggen')], {x:616,y:454},{x:616,y:404},'up','important',80,82), sourceAsset: 'Modern Interiors 48x48 / Living Room Singles 19' },
  { id: 'entry-mirror', label: 'Halspiegel', room: 'entry', render: { texture: 'round-mirror', x: 616, y: 358, layer: 'wall' }, interaction: interaction([action('look','Kijken'),action('hair','Haar controleren')], {x:616,y:454},{x:616,y:358},'up','observation',20,72), sourceAsset: 'Modern Interiors 48x48 / Living Room Singles 27' },
  { id: 'key-bowl', label: 'Schaaltje', room: 'entry', render: { texture: 'key-bowl', x: 602, y: 382, layer: 'surface' }, sourceAsset: 'QUOTIDIANO project-owned pixel prop' },
  { id: 'keys', label: 'Sleutels', room: 'entry', render: { texture: 'keys', x: 602, y: 382, layer: 'surface' }, interaction: interaction([action('take','Pakken'),action('leave','Neerleggen')], {x:616,y:454},{x:602,y:382},'up','inventory',70,78), sourceAsset: 'QUOTIDIANO project-owned pixel prop' },
  { id: 'mail', label: 'Post', room: 'entry', render: { texture: 'mail', x: 632, y: 386, layer: 'surface' }, interaction: interaction([action('take','Brief pakken'),action('read','Lezen'),action('store','Opbergen')], {x:616,y:454},{x:632,y:386},'up','inventory',70,72,'mailRead'), sourceAsset: 'Modern Interiors 48x48 / UI mail crop' },
  { id: 'coat', label: 'Jas', room: 'entry', render: { texture: 'coat', x: 638, y: 438, layer: 'wall' }, interaction: interaction([action('wear','Aantrekken'),action('remove','Uittrekken'),action('hang','Ophangen')], {x:606,y:470},{x:638,y:438},'right','inventory',70,70), sourceAsset: 'QUOTIDIANO project-owned pixel prop' },
  { id: 'umbrella', label: 'Paraplu', room: 'entry', render: { texture: 'umbrella', x: 638, y: 586 }, interaction: interaction([action('take','Pakken'),action('store','Terugzetten')], {x:606,y:590},{x:638,y:586},'right','inventory',70,70), sourceAsset: 'QUOTIDIANO project-owned pixel prop' },
  { id: 'entry-shoes', label: 'Schoenen', room: 'entry', render: { texture: 'shoes', x: 622, y: 548 }, interaction: interaction([action('wear','Aantrekken'),action('remove','Uittrekken')], {x:606,y:548},{x:622,y:548},'right','important',70,66), sourceAsset: 'Modern Interiors 48x48 / house prop crop' },
  { id: 'doormat', label: 'Deurmat', room: 'entry', render: { texture: 'doormat', x: 582, y: 628, layer: 'floor', scale: 1.5 }, sourceAsset: 'QUOTIDIANO project-owned pixel prop' },
  { id: 'front-door', label: 'Voordeur', room: 'entry', render: { texture: 'front-door', kind: 'sprite', x: 582, y: 651, frame: 0 }, interaction: interaction([action('open','Openen'),action('close','Sluiten'),action('unlock','Ontgrendelen'),action('lock','Vergrendelen'),action('leave-house','Naar buiten')], {x:582,y:610},{x:582,y:651},'down','critical',100,92,'doorLocked'), sourceAsset: 'Modern Interiors / animated door spritesheet' },

  // LAUNDRY
  { id: 'laundry-plant-left', label: 'Plant', room: 'laundry', render: { texture: 'plant', x: 710, y: 405 }, collision: {x:694,y:372,w:32,h:44}, sourceAsset: 'Modern Interiors 48x48 / Living Room Singles 15' },
  { id: 'washing-machine', label: 'Wasmachine', room: 'laundry', render: { texture: 'washing-machine', x: 744, y: 448 }, collision: {x:722,y:412,w:42,h:70}, interaction: interaction([action('toggle','Openen / sluiten'),action('load','Was laden'),action('wash','Programma starten'),action('remove','Was uitnemen')], {x:744,y:510},{x:744,y:448},'up','important',80,88,'laundryState'), sourceAsset: 'Modern Interiors 48x48 / Bathroom Singles' },
  { id: 'laundry-dryer', label: 'Droger', room: 'laundry', render: { texture: 'washing-machine', x: 800, y: 448 }, collision: {x:778,y:412,w:42,h:70}, sourceAsset: 'Modern Interiors 48x48 / Bathroom Singles (similar used as dryer stand-in)' },
  { id: 'laundry-shelf', label: 'Wasplank', room: 'laundry', render: { texture: 'bathroom-shelf', x: 858, y: 448 }, collision: {x:824,y:405,w:74,h:80}, interaction: interaction([action('take-detergent','Wasmiddel pakken'),action('store','Opbergen')], {x:856,y:512},{x:858,y:448},'up','important',80,82), sourceAsset: 'Modern Interiors 48x48 / Bathroom Singles 83' },
  { id: 'laundry-plant-right', label: 'Plant', room: 'laundry', render: { texture: 'plant', x: 894, y: 404 }, collision: {x:878,y:372,w:32,h:44}, sourceAsset: 'Modern Interiors 48x48 / Living Room Singles 15' },
  { id: 'laundry-basket', label: 'Wasmand', room: 'laundry', render: { texture: 'laundry-basket', x: 714, y: 570 }, collision: {x:696,y:538,w:36,h:48}, interaction: interaction([action('add-clothes','Kleding erin doen'),action('take-clothes','Kleding pakken')], {x:752,y:572},{x:714,y:570},'left','important',80,78), sourceAsset: 'Modern Interiors 48x48 / Bathroom Singles 95' },
  { id: 'drying-rack', label: 'Droogrek', room: 'laundry', render: { texture: 'towel-rack', x: 846, y: 562 }, collision: {x:830,y:528,w:32,h:44}, interaction: interaction([action('hang','Was ophangen'),action('take','Droge was pakken')], {x:804,y:584},{x:846,y:562},'right','important',80,72), sourceAsset: 'Modern Interiors 48x48 / Bathroom Singles 143' },
  { id: 'laundry-sink', label: 'Wasbak', room: 'laundry', render: { texture: 'bathroom-sink', x: 894, y: 576 }, collision: {x:854,y:532,w:74,h:64}, sourceAsset: 'Modern Interiors 48x48 / Bathroom Singles (similar used as utility sink)' }
];

export const createHouseInteractions = (): InteractionDefinition[] => HOUSE_OBJECTS.flatMap((object) => object.interaction ? [{
  id: object.id,
  objectId: object.label,
  room: object.room,
  ...object.interaction,
  actions: object.interaction.actions.map((entry) => ({ ...entry }))
}] : []);

export const houseObjectById = (id: string): HouseObjectDefinition | undefined => HOUSE_OBJECTS.find((object) => object.id === id);
