export interface RuntimeImageAsset { key: string; path: string }
export interface RuntimeSpriteAsset extends RuntimeImageAsset { frameWidth: number; frameHeight: number }

export const HOUSE_IMAGE_ASSETS: readonly RuntimeImageAsset[] = [
  { key:'floor-wood', path:'/assets/runtime/environment/floor_wood.png' },
  { key:'floor-parquet', path:'/assets/runtime/environment/floor_parquet.png' },
  { key:'floor-tile', path:'/assets/runtime/environment/floor_tile.png' },
  { key:'wall-light', path:'/assets/runtime/environment/wall_light.png' },
  { key:'bed', path:'/assets/runtime/objects/bed.png' },
  { key:'wardrobe', path:'/assets/runtime/objects/wardrobe.png' },
  { key:'wardrobe-closed-v3', path:'/assets/runtime/objects/wardrobe_closed_v3.png' },
  { key:'wardrobe-open-v3', path:'/assets/runtime/objects/wardrobe_open_v3.png' },
  { key:'bedroom-window', path:'/assets/runtime/objects/bedroom_window.png' },
  { key:'bedroom-rug', path:'/assets/runtime/objects/bedroom_rug.png' },
  { key:'bedroom-art', path:'/assets/runtime/objects/bedroom_art.png' },
  { key:'side-table', path:'/assets/runtime/objects/side_table.png' },
  { key:'bedside-lamp-on', path:'/assets/runtime/objects/bedside_lamp_on.png' },
  { key:'bedside-lamp-off', path:'/assets/runtime/objects/bedside_lamp_off.png' },
  { key:'alarm-clock', path:'/assets/runtime/objects/alarm_clock.png' },
  { key:'desk', path:'/assets/runtime/objects/desk.png' },
  { key:'laptop', path:'/assets/runtime/objects/laptop.png' },
  { key:'backpack', path:'/assets/runtime/objects/backpack.png' },
  { key:'shower', path:'/assets/runtime/objects/shower.png' },
  { key:'bathroom-sink', path:'/assets/runtime/objects/bathroom_sink.png' },
  { key:'bathroom-mirror', path:'/assets/runtime/objects/bathroom_mirror.png' },
  { key:'bathroom-mat', path:'/assets/runtime/objects/bathroom_mat.png' },
  { key:'bathroom-shelf', path:'/assets/runtime/objects/bathroom_shelf.png' },
  { key:'toilet', path:'/assets/runtime/objects/toilet.png' },
  { key:'towel-rack', path:'/assets/runtime/objects/towel_rack.png' },
  { key:'bathroom-bin', path:'/assets/runtime/objects/bathroom_bin.png' },
  { key:'toothbrush-cup', path:'/assets/runtime/objects/toothbrush_cup.png' },
  { key:'kitchen-counter', path:'/assets/runtime/objects/kitchen_counter.png' },
  { key:'dining-table', path:'/assets/runtime/objects/dining_table.png' },
  { key:'dining-chair', path:'/assets/runtime/objects/dining_chair.png' },
  { key:'breakfast-plate', path:'/assets/runtime/objects/breakfast_plate.png' },
  { key:'coffee-serving', path:'/assets/runtime/objects/coffee_serving.png' },
  { key:'sofa', path:'/assets/runtime/objects/sofa.png' },
  { key:'tv', path:'/assets/runtime/objects/tv.png' },
  { key:'floor-lamp', path:'/assets/runtime/objects/floor_lamp.png' },
  { key:'bookshelf', path:'/assets/runtime/objects/bookshelf.png' },
  { key:'coffee-table', path:'/assets/runtime/objects/coffee_table.png' },
  { key:'plant', path:'/assets/runtime/objects/plant.png' },
  { key:'string-lights', path:'/assets/runtime/objects/string_lights.png' },
  { key:'washing-machine', path:'/assets/runtime/objects/washing_machine.png' },
  { key:'laundry-basket', path:'/assets/runtime/objects/laundry_basket.png' },
  { key:'entry-console', path:'/assets/runtime/objects/entry_console.png' },
  { key:'round-mirror', path:'/assets/runtime/objects/round_mirror.png' },
  { key:'keys', path:'/assets/runtime/objects/keys.png' },
  { key:'phone', path:'/assets/runtime/objects/phone.png' },
  { key:'wallet', path:'/assets/runtime/objects/wallet.png' },
  { key:'key-bowl', path:'/assets/runtime/objects/key_bowl.png' },
  { key:'mail', path:'/assets/runtime/objects/mail.png' },
  { key:'coat', path:'/assets/runtime/objects/coat.png' },
  { key:'umbrella', path:'/assets/runtime/objects/umbrella.png' },
  { key:'doormat', path:'/assets/runtime/objects/doormat.png' },
  { key:'bread', path:'/assets/runtime/objects/bread.png' },
  { key:'toast', path:'/assets/runtime/objects/toast.png' },
  { key:'book', path:'/assets/runtime/objects/book.png' },
  { key:'mug', path:'/assets/runtime/objects/mug.png' },
  { key:'detergent', path:'/assets/runtime/objects/detergent.png' },
  { key:'clothes-bundle', path:'/assets/runtime/objects/clothes_bundle.png' },
  { key:'remote', path:'/assets/runtime/objects/remote.png' },
  { key:'shoes', path:'/assets/runtime/objects/shoes.png' }
] as const;

export const HOUSE_SPRITE_ASSETS: readonly RuntimeSpriteAsset[] = [
  { key:'fridge', path:'/assets/runtime/objects/fridge.png', frameWidth:96, frameHeight:144 },
  { key:'oven', path:'/assets/runtime/objects/oven.png', frameWidth:48, frameHeight:96 },
  { key:'coffee', path:'/assets/runtime/objects/coffee.png', frameWidth:48, frameHeight:96 },
  { key:'toaster', path:'/assets/runtime/objects/toaster.png', frameWidth:48, frameHeight:96 },
  { key:'front-door', path:'/assets/runtime/objects/front_door.png', frameWidth:96, frameHeight:144 },
  { key:'player', path:'/assets/runtime/characters/player_quotidiano.png', frameWidth:48, frameHeight:48 }
] as const;
