import type { InteractionDefinition, InteractionAction } from '../interactions/types';
import type { HouseObjectDefinition } from './types';

const action = (id: string, label: string, conditions: readonly string[] = [], effects: readonly string[] = []): InteractionAction => ({ id, label, conditions, effects });
const interaction = (
  actions: InteractionAction[],
  approachPoint: { x: number; y: number },
  actionPoint: { x: number; y: number },
  facing: InteractionDefinition['facing'],
  type: InteractionDefinition['type'] = 'important',
  priority = 80,
  radius = 88,
  persistentState?: string
): HouseObjectDefinition['interaction'] => ({ actions, approachPoint, actionPoint, facing, type, priority, radius, persistentState });

/**
 * Single source of truth for House V3 object placement, collisions and interactions.
 * Decorative objects may omit interaction; floor-layer objects may omit collision.
 */
export const HOUSE_OBJECTS: readonly HouseObjectDefinition[] = [
  // BEDROOM
  { id: 'bedroom-window', label: 'Raam en gordijnen', room: 'bedroom', render: { texture: 'bedroom-window', x: 224, y: 74, layer: 'wall' }, interaction: interaction([action('open-window','Raam openen'),action('close-window','Raam sluiten'),action('toggle-curtains','Gordijnen openen / sluiten'),action('look-outside','Naar buiten kijken')], {x:224,y:144},{x:224,y:74},'up','important',80,82,'windowOpen'), sourceAsset: 'Modern Interiors 48x48 / Bedroom Singles 119' },
  { id: 'bedroom-art', label: 'Poster', room: 'bedroom', render: { texture: 'bedroom-art', x: 116, y: 65, layer: 'wall', scale: 0.75 }, sourceAsset: 'Modern Interiors 48x48 / Bedroom Singles 479' },
  { id: 'bedroom-rug', label: 'Vloerkleed', room: 'bedroom', render: { texture: 'bedroom-rug', x: 186, y: 235, layer: 'floor', scale: 1.5 }, sourceAsset: 'Modern Interiors 48x48 / Bedroom Singles 381' },
  { id: 'bed', label: 'Bed', room: 'bedroom', render: { texture: 'bed', x: 105, y: 129 }, collision: {x:48,y:72,w:116,h:92}, interaction: interaction([action('sit','Op de rand zitten'),action('lie','Gaan liggen'),action('sleep','Slapen'),action('stand','Opstaan'),action('make','Bed opmaken')], {x:184,y:154},{x:145,y:142},'left','important',80,90,'bedMade'), sourceAsset: 'Modern Interiors 48x48 / Bedroom Singles' },
  { id: 'nightstand', label: 'Nachtkastje', room: 'bedroom', render: { texture: 'side-table', x: 184, y: 103 }, collision: {x:166,y:70,w:38,h:45}, interaction: interaction([action('open-drawer','Lade openen'),action('close-drawer','Lade sluiten'),action('examine','Bekijken')], {x:185,y:152},{x:184,y:103},'up','important',80,72,'nightstandOpen'), sourceAsset: 'Modern Interiors 48x48 / Living Room Singles 45' },
  { id: 'bedside-lamp', label: 'Nachtlamp', room: 'bedroom', render: { texture: 'bedside-lamp-on', x: 174, y: 76, layer: 'surface' }, interaction: interaction([action('toggle','Licht aan / uit')], {x:185,y:152},{x:174,y:80},'up','important',80,72), sourceAsset: 'Modern Interiors 48x48 / Bedroom lamp derivative' },
  { id: 'alarm-clock', label: 'Wekker', room: 'bedroom', render: { texture: 'alarm-clock', x: 193, y: 94, layer: 'surface', scale: 1.5 }, interaction: interaction([action('stop','Uitzetten'),action('snooze','Sluimeren'),action('set','Tijd instellen')], {x:185,y:152},{x:193,y:94},'up','important',80,72,'alarmState'), sourceAsset: 'QUOTIDIANO project-owned pixel prop' },
  { id: 'wardrobe', label: 'Kledingkast', room: 'bedroom', render: { texture: 'wardrobe-closed-v3', x: 314, y: 106 }, collision: {x:270,y:48,w:82,h:104}, interaction: interaction([action('toggle','Openen / sluiten'),action('dress','Kleding kiezen'),action('store-clothes','Kleding opbergen')], {x:300,y:184},{x:314,y:106},'up','important',80,92,'wardrobeOpen'), sourceAsset: 'Modern Interiors 48x48 / Bedroom Singles 538–539' },
  { id: 'desk', label: 'Bureau', room: 'bedroom', render: { texture: 'desk', x: 228, y: 218 }, collision: {x:179,y:188,w:98,h:48}, interaction: interaction([action('sit','Gaan zitten'),action('write','Schrijven'),action('stand','Opstaan')], {x:227,y:258},{x:228,y:218},'up','seat',50,86), sourceAsset: 'Modern Interiors 48x48 / Living Room Singles 29' },
  { id: 'laptop', label: 'Laptop', room: 'bedroom', render: { texture: 'laptop', x: 228, y: 199, layer: 'surface' }, interaction: interaction([action('toggle','Aan / uit'),action('email','E-mail openen')], {x:227,y:258},{x:228,y:202},'up','important',80,82,'laptopOn'), sourceAsset: 'QUOTIDIANO project-owned pixel prop' },
  { id: 'backpack', label: 'Rugzak', room: 'bedroom', render: { texture: 'backpack', x: 317, y: 235 }, interaction: interaction([action('take','Pakken'),action('leave','Neerzetten'),action('inspect','Inhoud bekijken')], {x:302,y:250},{x:317,y:235},'right','inventory',70,70), sourceAsset: 'Modern Interiors 48x48 / Bedroom Singles 437' },

  // BATHROOM
  { id: 'bathroom-mat', label: 'Badmat', room: 'bathroom', render: { texture: 'bathroom-mat', x: 515, y: 238, layer: 'floor' }, sourceAsset: 'Modern Interiors 48x48 / Bathroom Singles 77' },
  { id: 'bathroom-mirror', label: 'Spiegel', room: 'bathroom', render: { texture: 'bathroom-mirror', x: 420, y: 72, layer: 'wall' }, interaction: interaction([action('look','Kijken'),action('hair','Haar doen')], {x:420,y:164},{x:420,y:72},'up','observation',20,76), sourceAsset: 'Modern Interiors 48x48 / Bathroom Singles 66' },
  { id: 'bathroom-sink', label: 'Wastafel', room: 'bathroom', render: { texture: 'bathroom-sink', x: 420, y: 115 }, collision: {x:379,y:68,w:82,h:72}, interaction: interaction([action('wash-hands','Handen wassen'),action('wash-face','Gezicht wassen')], {x:420,y:169},{x:420,y:115},'up','important',80,80), sourceAsset: 'Modern Interiors 48x48 / Bathroom Singles' },
  { id: 'toothbrush', label: 'Tandenborstel', room: 'bathroom', render: { texture: 'toothbrush-cup', x: 458, y: 112, layer: 'surface' }, interaction: interaction([action('take','Pakken'),action('brush','Tanden poetsen'),action('store','Terugzetten')], {x:455,y:169},{x:458,y:112},'up','inventory',70,72), sourceAsset: 'QUOTIDIANO project-owned pixel prop' },
  { id: 'shower', label: 'Douche', room: 'bathroom', render: { texture: 'shower', x: 540, y: 113 }, collision: {x:500,y:48,w:76,h:112}, interaction: interaction([action('shower','Douchen')], {x:492,y:174},{x:526,y:166},'right','important',80,92,'showeredToday'), sourceAsset: 'Modern Interiors 48x48 / Bathroom Singles' },
  { id: 'toilet', label: 'Toilet', room: 'bathroom', render: { texture: 'toilet', x: 404, y: 220 }, collision: {x:383,y:178,w:42,h:78}, interaction: interaction([action('use','Gebruiken'),action('flush','Doorspoelen')], {x:454,y:220},{x:404,y:220},'left','important',80,76), sourceAsset: 'Modern Interiors 48x48 / Bathroom Singles' },
  { id: 'bathroom-shelf', label: 'Badkamerkast', room: 'bathroom', render: { texture: 'bathroom-shelf', x: 552, y: 218 }, collision: {x:523,y:184,w:54,h:70}, interaction: interaction([action('open','Openen'),action('take-products','Verzorgingsproducten pakken'),action('close','Sluiten')], {x:506,y:232},{x:552,y:218},'right','important',80,78), sourceAsset: 'Modern Interiors 48x48 / Bathroom Singles 83' },
  { id: 'towel-rack', label: 'Handdoek', room: 'bathroom', render: { texture: 'towel-rack', x: 470, y: 226 }, interaction: interaction([action('take','Pakken'),action('use','Afdrogen'),action('hang','Ophangen')], {x:468,y:252},{x:470,y:226},'down','inventory',70,66), sourceAsset: 'Modern Interiors 48x48 / Bathroom Singles 143' },
  { id: 'bathroom-bin', label: 'Prullenbak', room: 'bathroom', render: { texture: 'bathroom-bin', x: 545, y: 258 }, interaction: interaction([action('discard','Afval weggooien')], {x:520,y:252},{x:545,y:258},'right','important',80,65), sourceAsset: 'Modern Interiors 48x48 / Bathroom Singles 138' },

  // KITCHEN / DINING
  { id: 'oven', label: 'Fornuis', room: 'kitchen', render: { texture: 'oven', kind: 'sprite', x: 636, y: 108, frame: 0 }, collision: {x:612,y:58,w:54,h:84}, interaction: interaction([action('toggle','Aan / uit'),action('cook','Koken')], {x:640,y:174},{x:636,y:108},'up','important',80,86,'ovenOn'), sourceAsset: 'Modern Interiors 48x48 / Kitchen Singles' },
  { id: 'kitchen-sink', label: 'Aanrecht en gootsteen', room: 'kitchen', render: { texture: 'kitchen-counter', x: 718, y: 106 }, collision: {x:672,y:62,w:92,h:72}, interaction: interaction([action('wash-hands','Handen wassen'),action('wash-food','Eten wassen'),action('wash-dishes','Afwas doen')], {x:718,y:174},{x:718,y:106},'up','important',80,86), sourceAsset: 'Modern Interiors 48x48 / Kitchen Singles' },
  { id: 'coffee', label: 'Koffiezetapparaat', room: 'kitchen', render: { texture: 'coffee', kind: 'sprite', x: 778, y: 113, frame: 0, layer: 'surface' }, interaction: interaction([action('brew','Koffie zetten'),action('take','Kopje pakken')], {x:778,y:174},{x:778,y:113},'up','important',80,82,'coffeeReady'), sourceAsset: 'Modern Interiors 48x48 / Kitchen Singles' },
  { id: 'toaster', label: 'Broodrooster', room: 'kitchen', render: { texture: 'toaster', kind: 'sprite', x: 822, y: 113, frame: 0, layer: 'surface' }, interaction: interaction([action('toast','Brood roosteren')], {x:820,y:174},{x:822,y:113},'up','important',80,82,'toastReady'), sourceAsset: 'Modern Interiors 48x48 / Kitchen Singles' },
  { id: 'fridge', label: 'Koelkast', room: 'kitchen', render: { texture: 'fridge', kind: 'sprite', x: 880, y: 112, frame: 0 }, collision: {x:849,y:48,w:64,h:116}, interaction: interaction([action('toggle','Openen / sluiten'),action('take-breakfast','Brood pakken'),action('put-back','Terugzetten')], {x:878,y:184},{x:880,y:112},'up','important',80,96,'fridgeOpen'), sourceAsset: 'Modern Interiors 48x48 / Kitchen Singles' },
  { id: 'kitchen-bin', label: 'Afvalbak', room: 'kitchen', render: { texture: 'bathroom-bin', x: 902, y: 194 }, interaction: interaction([action('discard','Afval weggooien')], {x:872,y:202},{x:902,y:194},'right','important',80,68), sourceAsset: 'Modern Interiors 48x48 / Bathroom Singles 138' },
  { id: 'dining-table', label: 'Eettafel', room: 'kitchen', render: { texture: 'dining-table', x: 786, y: 286 }, collision: {x:738,y:244,w:96,h:72}, interaction: interaction([action('place-breakfast','Ontbijt neerzetten'),action('sit','Gaan zitten'),action('eat','Ontbijten'),action('drink','Drinken'),action('stand','Opstaan')], {x:702,y:328},{x:702,y:286},'up','seat',50,98,'breakfastEaten'), sourceAsset: 'Modern Interiors 48x48 / Kitchen Singles' },
  { id: 'dining-chair-left', label: 'Eetkamerstoel', room: 'kitchen', render: { texture: 'dining-chair', x: 702, y: 286 }, collision: {x:684,y:260,w:36,h:42}, sourceAsset: 'Modern Interiors 48x48 / Living Room Singles' },
  { id: 'dining-chair-right', label: 'Eetkamerstoel', room: 'kitchen', render: { texture: 'dining-chair', x: 868, y: 286, flipX: true }, collision: {x:850,y:260,w:36,h:42}, sourceAsset: 'Modern Interiors 48x48 / Living Room Singles' },
  { id: 'breakfast-plate', label: 'Ontbijtbord', room: 'kitchen', render: { texture: 'breakfast-plate', x: 775, y: 270, layer: 'surface', visible: false }, sourceAsset: 'Modern Interiors 48x48 / Kitchen Singles' },
  { id: 'coffee-serving', label: 'Koffiekop', room: 'kitchen', render: { texture: 'coffee-serving', x: 806, y: 272, layer: 'surface', visible: false }, sourceAsset: 'Modern Interiors 48x48 / Kitchen Singles' },
  { id: 'kitchen-plant', label: 'Keukenplant', room: 'kitchen', render: { texture: 'plant', x: 900, y: 300 }, collision: {x:884,y:264,w:32,h:44}, interaction: interaction([action('observe','Bekijken'),action('water','Water geven')], {x:868,y:318},{x:900,y:300},'right','observation',20,66), sourceAsset: 'Modern Interiors 48x48 / Living Room Singles 15' },

  // LIVING ROOM
  { id: 'living-lights', label: 'Lichtsnoer', room: 'living', render: { texture: 'string-lights', x: 258, y: 326, layer: 'wall', scale: 1.5 }, sourceAsset: 'Modern Interiors 48x48 / Living Room Singles 12' },
  { id: 'living-rug', label: 'Vloerkleed', room: 'living', render: { texture: 'bedroom-rug', x: 258, y: 502, layer: 'floor', scale: 2 }, sourceAsset: 'Modern Interiors 48x48 / Bedroom Singles 381' },
  { id: 'tv', label: 'Televisie', room: 'living', render: { texture: 'tv', x: 258, y: 357 }, collision: {x:214,y:316,w:88,h:70}, interaction: interaction([action('toggle','Aan / uit'),action('watch','Even kijken')], {x:258,y:411},{x:258,y:357},'up','important',80,86,'tvOn'), sourceAsset: 'Modern Interiors 48x48 / Living Room Singles' },
  { id: 'bookshelf', label: 'Boekenkast', room: 'living', render: { texture: 'bookshelf', x: 72, y: 390 }, collision: {x:52,y:346,w:40,h:76}, interaction: interaction([action('examine','Bekijken'),action('take-book','Boek pakken'),action('read-book','Lezen'),action('return-book','Terugzetten')], {x:114,y:395},{x:72,y:390},'left','important',80,82), sourceAsset: 'Modern Interiors 48x48 / Living Room Singles 122' },
  { id: 'living-plant', label: 'Kamerplant', room: 'living', render: { texture: 'plant', x: 420, y: 387 }, collision: {x:405,y:352,w:30,h:50}, interaction: interaction([action('observe','Bekijken'),action('water','Water geven')], {x:390,y:414},{x:420,y:387},'right','observation',20,70), sourceAsset: 'Modern Interiors 48x48 / Living Room Singles 15' },
  { id: 'coffee-table', label: 'Salontafel', room: 'living', render: { texture: 'coffee-table', x: 258, y: 458 }, collision: {x:213,y:426,w:90,h:55}, interaction: interaction([action('place-item','Iets neerzetten'),action('take-item','Iets pakken')], {x:335,y:470},{x:258,y:458},'left','important',80,82), sourceAsset: 'Modern Interiors 48x48 / Living Room Singles 51' },
  { id: 'sofa', label: 'Bank', room: 'living', render: { texture: 'sofa', x: 258, y: 548 }, collision: {x:207,y:530,w:102,h:42}, interaction: interaction([action('sit','Zitten'),action('relax','Ontspannen'),action('stand','Opstaan')], {x:258,y:598},{x:258,y:540},'up','seat',50,92), sourceAsset: 'Modern Interiors 48x48 / Living Room Singles' },
  { id: 'living-lamp', label: 'Staande lamp', room: 'living', render: { texture: 'floor-lamp', x: 414, y: 550 }, collision: {x:398,y:515,w:32,h:60}, interaction: interaction([action('toggle','Aan / uit')], {x:380,y:576},{x:414,y:550},'right','important',80,76,'livingLightOn'), sourceAsset: 'Modern Interiors 48x48 / Living Room Singles 86' },
  { id: 'side-table', label: 'Bijzettafel', room: 'living', render: { texture: 'side-table', x: 112, y: 550 }, collision: {x:94,y:520,w:36,h:45}, interaction: interaction([action('place-item','Iets neerzetten'),action('take-item','Iets pakken')], {x:148,y:565},{x:112,y:550},'left','important',80,68), sourceAsset: 'Modern Interiors 48x48 / Living Room Singles 45' },

  // ENTRY / HALL
  { id: 'entry-console', label: 'Halmeubel', room: 'entry', render: { texture: 'entry-console', x: 548, y: 380 }, collision: {x:502,y:338,w:94,h:70}, interaction: interaction([action('examine','Bekijken'),action('place-item','Iets neerleggen')], {x:548,y:432},{x:548,y:380},'up','important',80,82), sourceAsset: 'Modern Interiors 48x48 / Living Room Singles 19' },
  { id: 'entry-mirror', label: 'Halspiegel', room: 'entry', render: { texture: 'round-mirror', x: 630, y: 350, layer: 'wall' }, interaction: interaction([action('look','Kijken'),action('hair','Haar controleren')], {x:626,y:414},{x:630,y:350},'up','observation',20,72), sourceAsset: 'Modern Interiors 48x48 / Living Room Singles 27' },
  { id: 'key-bowl', label: 'Schaaltje', room: 'entry', render: { texture: 'key-bowl', x: 535, y: 354, layer: 'surface' }, sourceAsset: 'QUOTIDIANO project-owned pixel prop' },
  { id: 'keys', label: 'Sleutels', room: 'entry', render: { texture: 'keys', x: 535, y: 354, layer: 'surface' }, interaction: interaction([action('take','Pakken'),action('leave','Neerleggen')], {x:548,y:432},{x:535,y:354},'up','inventory',70,78), sourceAsset: 'QUOTIDIANO project-owned pixel prop' },
  { id: 'mail', label: 'Post', room: 'entry', render: { texture: 'mail', x: 568, y: 359, layer: 'surface' }, interaction: interaction([action('take','Brief pakken'),action('read','Lezen'),action('store','Opbergen')], {x:548,y:432},{x:568,y:359},'up','inventory',70,72,'mailRead'), sourceAsset: 'Modern Interiors 48x48 / UI mail crop' },
  { id: 'coat', label: 'Jas', room: 'entry', render: { texture: 'coat', x: 638, y: 527, layer: 'wall' }, interaction: interaction([action('wear','Aantrekken'),action('remove','Uittrekken'),action('hang','Ophangen')], {x:610,y:540},{x:638,y:527},'right','inventory',70,70), sourceAsset: 'QUOTIDIANO project-owned pixel prop' },
  { id: 'umbrella', label: 'Paraplu', room: 'entry', render: { texture: 'umbrella', x: 638, y: 588 }, interaction: interaction([action('take','Pakken'),action('store','Terugzetten')], {x:610,y:590},{x:638,y:588},'right','inventory',70,70), sourceAsset: 'QUOTIDIANO project-owned pixel prop' },
  { id: 'doormat', label: 'Deurmat', room: 'entry', render: { texture: 'doormat', x: 582, y: 628, layer: 'floor', scale: 1.5 }, sourceAsset: 'QUOTIDIANO project-owned pixel prop' },
  { id: 'front-door', label: 'Voordeur', room: 'entry', render: { texture: 'front-door', kind: 'sprite', x: 582, y: 651, frame: 0 }, interaction: interaction([action('open','Openen'),action('close','Sluiten'),action('unlock','Ontgrendelen'),action('lock','Vergrendelen'),action('leave-house','Naar buiten')], {x:582,y:610},{x:582,y:651},'down','critical',100,92,'doorLocked'), sourceAsset: 'Modern Interiors / animated door spritesheet' },

  // LAUNDRY
  { id: 'washing-machine', label: 'Wasmachine', room: 'laundry', render: { texture: 'washing-machine', x: 742, y: 450 }, collision: {x:721,y:414,w:42,h:70}, interaction: interaction([action('toggle','Openen / sluiten'),action('load','Was laden'),action('wash','Programma starten'),action('remove','Was uitnemen')], {x:742,y:510},{x:742,y:450},'up','important',80,88,'laundryState'), sourceAsset: 'Modern Interiors 48x48 / Bathroom Singles' },
  { id: 'laundry-shelf', label: 'Wasplank', room: 'laundry', render: { texture: 'bathroom-shelf', x: 864, y: 448 }, collision: {x:824,y:405,w:76,h:80}, interaction: interaction([action('take-detergent','Wasmiddel pakken'),action('store','Opbergen')], {x:810,y:465},{x:864,y:448},'right','important',80,82), sourceAsset: 'Modern Interiors 48x48 / Bathroom Singles 83' },
  { id: 'laundry-basket', label: 'Wasmand', room: 'laundry', render: { texture: 'laundry-basket', x: 835, y: 565 }, collision: {x:817,y:532,w:36,h:50}, interaction: interaction([action('add-clothes','Kleding erin doen'),action('take-clothes','Kleding pakken')], {x:795,y:570},{x:835,y:565},'right','important',80,78), sourceAsset: 'Modern Interiors 48x48 / Bathroom Singles 95' },
  { id: 'drying-rack', label: 'Droogrek', room: 'laundry', render: { texture: 'towel-rack', x: 884, y: 590 }, collision: {x:868,y:555,w:32,h:45}, interaction: interaction([action('hang','Was ophangen'),action('take','Droge was pakken')], {x:840,y:620},{x:884,y:590},'right','important',80,72), sourceAsset: 'Modern Interiors 48x48 / Bathroom Singles 143' }
];

export const createHouseInteractions = (): InteractionDefinition[] => HOUSE_OBJECTS.flatMap((object) => object.interaction ? [{
  id: object.id,
  objectId: object.label,
  room: object.room,
  ...object.interaction,
  actions: object.interaction.actions.map((entry) => ({ ...entry }))
}] : []);

export const houseObjectById = (id: string): HouseObjectDefinition | undefined => HOUSE_OBJECTS.find((object) => object.id === id);
